# Generated by Django 4.2.17 on 2024-12-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tSquad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidnces',
            new_name='Incidences',
        ),
    ]
